### ISSUE TITLE
Brx 14 with Starter Store and PageModel APIs enabled not working

### ISSUE THREAD

**Issue by andrerinaldi** [bloomreach/bloomreach-reference-spa#1]
Hi,

I installed the Starter Store plugin, configured it to work with commercetools and exposed PageModel APIs from the mount starterstoreboot. But this react application is not working out of the box, it says that all the needed components are missing, when I was said that it could have been a valid starting point as a starter store SPA frontend.

The standard brx channel exposed on localhost:8080/site/starterstoreboot works fine so the ecommerce configuration is ok.

Am I missing something? Am I doing something wrong?

Thank you.

**Comment by rlpmartins** [comment]
Hi, 

Just to let you know that from brXM v14.3 we have released the brX GraphQL Service which combines the APIs from Bloomreach’s Search and Merchandising and commerce platforms into one single GraphQL schema for headless front-end development. This is an evolution of our B2C Commerce Accelerator covering the same use cases and currently supporting commercetools and SAP OOTB. You can find more information in our documentation: [Introduction to brX GraphQL Service](https://documentation.bloomreach.com/14/library/solutions/commerce-starterstore/graphql-service/introduction.html)

Additionally you can also have a look at our [Commerce React Components library](https://documentation.bloomreach.com/14/library/solutions/commerce-starterstore/commerce-react-components/introduction.html) to integrate the brX GraphQL Service with a React SPA.

Ricardo,
Technical Product Manager
